apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 0.0.1
appVersion: 2.3.3
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: truecharts
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
dependencies:
  - name: cert-manager
    repository:  "https://charts.jetstack.io"
    version: v1.1.0
