## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
image:
  repository: nextcloud
  tag: 19.0.3-apache
  pullPolicy: IfNotPresent

nextcloud:
  host: nextcloud.kube.home
  username: admin
  password: changeme
  datadir: /var/www/html/data
  strategy: "Recreate"

redis:
  enabled: false
  usePassword: false

service:
  nodePort: 9001
